[package]
name = "mind"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
syn = { version = "2", features = ["full"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
walkdir = "2"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
anyhow = "1"
thiserror = "1"
ahnlich_client_rs = "0.3.0"
ahnlich_types = "=0.2.2"
toml = "1.1"
globset = "0.4"