[package]
name = "devmind"
version = "0.1.0"
edition = "2024"

[lib]
name = "devmind"
path = "src/lib.rs"

[[bin]]
name = "devmind"
path = "src/main.rs"

[[bench]]
name = "parsing_bench"
harness = false

[[bench]]
name = "ahnlich_bench"
harness = false

[features]
mem_profile = []

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
syn = { version = "2", features = ["full", "visit"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
walkdir = "2"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
anyhow = "1"
thiserror = "1"
ahnlich_client_rs = "0.3.0"
ahnlich_types = "=0.3.0"
toml = "1.1"
globset = "0.4"
rustc_lexer = { package = "ra-ap-rustc_lexer", version = "0.174.0"}
colored = "2"
indicatif = "0.17"
directories = "5"
futures = "0.3"
tokenizers = "0.20"


[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio", "html_reports"] }
